name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Build .jar
        run: ./build-jar.sh
      - name: Upload .jar
        uses: actions/upload-artifact@v2.3.0
        with:
          name: jar
          path: proofbuilder/target/proofbuilder-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          if-no-files-found: error

  windows:
    needs: jar
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Download .jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: proofbuilder/target
      - name: Build release .zip
        shell: bash
        run: ./build-windows.sh
      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Windows release
          path: proofbuilder/ProofBuilder-windows.zip
          if-no-files-found: error

  macos:
    needs: jar
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Download .jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: proofbuilder/target
      - name: Install Apple Developer ID
        env:
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: |
          echo -n "$APPLE_DEVELOPER_ID" | base64 --decode --output apple_developer_id.p12
          security create-keychain -p '' apple_developer_id.keychain-db
          security set-keychain-settings -lut 21600 apple_developer_id.keychain-db
          security unlock-keychain -p '' apple_developer_id.keychain-db
          security import apple_developer_id.p12 -P '' -A -t cert -f pkcs12 -k apple_developer_id.keychain-db -T /usr/bin/codesign
          security list-keychains -d user -s apple_developer_id.keychain-db
          security list-keychains -d user
          security find-certificate -a -c 'Developer ID'
          security unlock-keychain -p '' apple_developer_id.keychain-db
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k '' apple_developer_id.keychain-db
          xcrun notarytool store-credentials APPLE_ID_PASSWORD --apple-id bart.a.jacobs@gmail.com --team-id 6C42VUP45N --password "$APPLE_ID_PASSWORD"
      - name: Build release .zip
        shell: bash
        run: |
          set -x
          cd proofbuilder
          jpackage --verbose -p target/proofbuilder-0.0.1-SNAPSHOT-jar-with-dependencies.jar -m proofbuilder/proofbuilder.ProofBuilderFrame --name ProofBuilder --type app-image --mac-sign | tee log.txt
          zip -ry ProofBuilder-macos-unstapled.zip ProofBuilder.app
          xcrun notarytool submit ProofBuilder-macos-unstapled.zip --keychain-profile APPLE_ID_PASSWORD --wait
          xcrun stapler staple ProofBuilder.app
          zip -ry ProofBuilder-macos.zip ProofBuilder.app
      - name: Upload log
        if: ${{ cancelled() }}
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Log
          path: proofbuilder/log.txt
      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: macOS release
          path: proofbuilder/ProofBuilder-macos.zip
          if-no-files-found: error

  ubuntu:
    needs: jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Download .jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: proofbuilder/target
      - name: Build release .zip
        run: ./build-linux.sh
      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Linux release
          path: proofbuilder/ProofBuilder-linux.txz
          if-no-files-found: error
