name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Build .jar
        run: ./build-jar.sh
      - name: Upload .jar
        uses: actions/upload-artifact@v2.3.0
        with:
          name: jar
          path: proofbuilder/target/proofbuilder-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          if-no-files-found: error

  windows:
    needs: jar
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Download .jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: target
      - name: Build release .zip
        shell: bash
        run: ./build-windows.sh
      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Windows release
          path: proofbuilder/ProofBuilder-windows.zip
          if-no-files-found: error

  macos:
    needs: jar
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Download .jar
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: target
      - name: Build release .zip
        shell: bash
        run: ./build-macos.sh
      - name: Upload release .zip
        uses: actions/upload-artifact@v2.3.0
        with:
          name: macOS release
          path: proofbuilder/ProofBuilder-macos.zip
          if-no-files-found: error

  ubuntu:
    needs: jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Build release .zip
        run: ./build-linux.sh
      - name: Upload release .zip
        uses: artifacts/upload-artifact@v2.3.0
        with:
          name: Linux release
          path: proofbuilder/ProofBuilder-linux.txz
          if-no-files-found: error
